// <auto-generated />
namespace Application.Marvel.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class cria_tabelas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cria_tabelas));
        
        string IMigrationMetadata.Id
        {
            get { return "201611252028477_cria_tabelas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
